### ISSUE TITLE
Wrong output type for compiled script

### ISSUE THREAD

**Issue by Krumpet** [studoot/ps2exe#1] opened 2017-05-23 16:35 UTC
I also posted this on technet, I apologize if the duplicity is annoying:
I have a script which runs the msdl library compiled for windows. When I'm downloading a file by running the .ps1 script, the output shows download percentage and updates as it progresses.
However when I run the exe compiled from the .ps1 script, the output is in red, prefaced with "ERROR: ", and keeps printing and scrolling the screen, rather than updating the same line.
Is it possible to manipulate the output type of the script or the specific command so it appears as intended?
Thanks.

**Comment by studoot** [comment] 2017-06-06 12:34
@Krumpet - could you post your ps1 file, or at least the part of it that produces this output, please?

**Comment by Krumpet** [comment] 2017-06-06 14:42
Yeah, basically the command is:
```
cmd /c .\msdl.exe -s2 $address -o $filename '2>&1' | ForEach-Object {
# re-parse the output line-by-line, due to the problem I described
}

```

The 2>&1 redirection is because MSDL outputs to stderr by default. This wasn't needed when running my script, but as a compiled EXE I've had to redirect to stdout, and then based on the line being written, either write-host it with no newline (to overwrite previous progress report), or as a new line with write-output.

My script is here:
https://github.com/Krumpet/OVSDownloader

It uses the msdl program which can be found [here](http://msdl.sourceforge.net/)

**Comment by studoot** [comment] 2017-06-07 14:52
OK, I understand what the problem is... And why there isn't a good/easy fix for it...

1. If you make `msdl` output its progress to stdout, then that output gets converted to objects by the Powershell processing engine. Each line of output (terminated by \r, \r\n or \n) is converted to a string object and passed along as an 'output object', the same way as in a Powershell pipeline. This process loses the line terminators, so that you can't tell if a string is terminated with a carriage-return/line-feed pair or, as is the case for the 'progress' lines, where each line of output overwrites the previous one, just a carriage-return.

    This behaviour cannot be changed, as it's a fundamental part of how Powershell works.

1. If you let `msdl` output its progress to stderr, (i.e. lose the `2>&1`), then, with a hack to `ps2exe`, it *is* possible to display the output in the way that you see when you run it directly in a Powershell script. However, all error lines (and warning, debug etc lines) would appear the same as standard output lines. This is possible because the error (and warning and debug and verbose) streams are treated as streams of text, the same way that stdout is under `cmd` or Unix shells.

So - no solution that's 100% good... And this is part of why (I think) Powershell supplies `Write-Progress` - give a specific mechanism for displaying progress rather than overloading text output using a bit of a hack (that carriage-return operates the way it does).

I implemented the following loop for `curl` which uses `Write-Progress` rather than what `curl` normally does (which is basically the same thing as `msdl`). Of course, PS2EXE doesn't support Write-Progress either, but that's probably a more sustainable way of showing progress...

```Powershell
$dest="test.file"
$link="https://www.scootersoftware.com/BCompare-4.2.2.22384.exe"

cmd /c C:\msys64\mingw64\bin\curl.exe -o $dest $link "2>&1"  | ForEach-Object {
   $bits = (-split $_)
   [int]$pc = $null
   if (($bits.Length -gt 0) -and ([int32]::TryParse($bits[0] , [ref]$pc )))
   {
      Write-Progress -activity "Downloading $link to $dest" -percentComplete $pc
   }
}
```

**Comment by Krumpet** [comment] 2017-06-07 15:14
Thanks for the explanation! Your loop is different than mine, I'll have a look into it.

**Comment by studoot** [comment] 2017-06-07 16:40
After a little more experimentation, I realise I was wrong when I said I had a hack to make output to stderr work. Powershell messes with strings sent through stderr as well, so I can't make that work reliably either... Everything's broken!

For that reason, I'm going to close this issue - there's nothing I can do to fix your problem, unfortunately :-(

**Closed as completed by studoot** 2017-06-07 16:40 UTC
